version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: backend-app
    ports:
      - "4141:4141"
    networks:
      - app-network

  frontend:
    build:
      context: .
    container_name: frontend-app
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge